name: raugm2023             
channels:                   
  - conda-forge             
dependencies:               
  - python=3.10             
  - openssl=3.1.4           
  - numpy=1.26.0            
  - xarray=2023.10.1        
  - matplotlib=3.8.0        
  - cartopy=0.22.0          
  - pytz=2023.3.post1       
  - geopandas=0.14.0        
  - netCDF4=1.6.5           
  - pillow 

